#!/bin/zsh
cat <<EOF | ssh yagni -T
  setopt verbose
  set -e
  if [ ! -d hillshade.io ] ; then
    git init
    git remote add -f origin https://github.com/arctair/hillshade.io
  fi
  cd hillshade.io
  if ! grep api .git/info/sparse-checkout 2&>/dev/null ; then
    git config core.sparseCheckout true
    echo api >> .git/info/sparse-checkout
  fi
  git fetch origin main
  git reset origin/main --hard
  cd api
  npm i
  if [ -L $HOME/.config/systemd/user/api.hillshade.io.service ] ; then
    systemctl stop --user api.hillshade.io
    systemctl disable --user api.hillshade.io
  fi
  ln -s $HOME/hillshade.io/api/scripts/api.hillshade.io.service $HOME/.config/systemd/user
  systemctl enable --user api.hillshade.io
EOF
