#!/bin/zsh
cat <<EOF | ssh yagni -T
    cd /home/arctair/hillshade.io
    git fetch
    git reset origin/main --hard
    systemctl daemon-reload --user
    systemctl restart api.hillshade.io --user
EOF
