#!/bin/zsh
cat <<EOF | ssh yagni -T
  if [ ! -d hillshade.io ] ; then
    git init
    git remote add -f origin https://github.com/arctair/hillshade.io
  fi
  cd hillshade.io
  if ! grep apits .git/info/sparse-checkout 2&>/dev/null ; then
    git config core.sparseCheckout true
    echo apits >> .git/info/sparse-checkout
  fi
  git pull origin main
  cd apits
  npm i
  ln -s $HOME/hillshade.io/apits/scripts/api.hillshade.io.service $HOME/.config/systemd/user
  systemctl enable api.hillshade.io --user
EOF
